[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/run/supervisord.pid

[program:php-fpm]
command=/usr/local/sbin/php-fpm --nodaemonize
priority=10
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:avatar-consume]
command=/usr/local/bin/php /var/www/html/bin/console app:avatar:consume
directory=/var/www/html
user=www-data
priority=20
autostart=true
autorestart=true
startsecs=3
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
